# Generated by Django 3.2 on 2021-04-26 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project1Authors',
            fields=[
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'db_table': 'project1_authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1BookCopies',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_of_copies', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project1_book_copies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1BookCopiesLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, max_length=12, null=True)),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('no_of_copies', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project1_book_copies_load',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1BookLoans',
            fields=[
                ('loan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_out', models.DateField(blank=True, null=True)),
                ('date_in', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project1_book_loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1Books',
            fields=[
                ('isbn10', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('isbn13', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('authro', models.CharField(blank=True, max_length=128, null=True)),
                ('cover', models.CharField(blank=True, max_length=128, null=True)),
                ('publisher', models.CharField(blank=True, max_length=128, null=True)),
                ('pages', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project1_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1BooksLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.CharField(blank=True, max_length=10, null=True)),
                ('isbn13', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('authro', models.CharField(blank=True, max_length=128, null=True)),
                ('cover', models.CharField(blank=True, max_length=128, null=True)),
                ('publisher', models.CharField(blank=True, max_length=128, null=True)),
                ('pages', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project1_books_load',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1BooksTemptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_no', models.BigIntegerField()),
                ('book_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'project1_books_temptable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1Borrowers',
            fields=[
                ('card_no', models.CharField(max_length=26, primary_key=True, serialize=False)),
                ('ssn', models.CharField(blank=True, max_length=26, null=True)),
                ('first_name', models.CharField(max_length=26)),
                ('last_name', models.CharField(max_length=26)),
                ('email', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=26)),
                ('state', models.CharField(max_length=26)),
                ('phone', models.CharField(blank=True, max_length=26, null=True)),
            ],
            options={
                'db_table': 'project1_borrowers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1BorrowersLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id0000id', models.CharField(blank=True, max_length=26, null=True)),
                ('ssn', models.CharField(blank=True, max_length=26, null=True)),
                ('first_name', models.CharField(blank=True, max_length=26, null=True)),
                ('last_name', models.CharField(blank=True, max_length=26, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=26, null=True)),
                ('state', models.CharField(blank=True, max_length=26, null=True)),
                ('phone', models.CharField(blank=True, max_length=26, null=True)),
            ],
            options={
                'db_table': 'project1_borrowers_load',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1BorrowerTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_no', models.BigIntegerField()),
                ('card_no', models.CharField(max_length=26)),
            ],
            options={
                'db_table': 'project1_borrower_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1LibraryBranch',
            fields=[
                ('branch_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'project1_library_branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1LibraryBranchLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.BigIntegerField(blank=True, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=26, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'project1_library_branch_load',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1BookAuthors',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='libraryapp.project1authors')),
            ],
            options={
                'db_table': 'project1_book_authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project1Fines',
            fields=[
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='libraryapp.project1bookloans')),
                ('fine_amt', models.BigIntegerField(blank=True, null=True)),
                ('paid', models.CharField(blank=True, max_length=28, null=True)),
            ],
            options={
                'db_table': 'project1_fines',
                'managed': False,
            },
        ),
    ]
